version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: ${APP_NAME}
    volumes:
      - ".env:/app/.env"
      - "./public/swagger.json:/app/public/swagger.json"
  db:
    image: postgres:14.4-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
        - "5432:5432"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
